### rasp-test-mybatis-plus sql注入
GET http://localhost:8080/rasp-test-mybatis-plus/user?tid=' or 1=1 and '123'='123

### rasp-test-mybatis-plus sql注入
GET http://localhost:8080/rasp-test-mybatis-plus/all